spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 8762
spring: 
   profiles: dev
   application: 
    name: microservicecloud-config-dept-client
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///clouddb01?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: club.bigtian
  company.name: www.bigtian.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8763
spring: 
   profiles: test
   application: 
    name: microservicecloud-config-dept-client
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///clouddb03?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: club.bigtian
  company.name: www.bigtian.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$
